### PR TITLE
Moved base path to requestBasics, inlined paths

### PR DESCRIPTION
**Pull request by igor-vovk**
Please see commit

### CODE REVIEW

**Comment by pedrorijo91** [comment]
what's the motivation for this PR?

There are a lot of braking changes when you change a public method signature. Unless there's a very strong reason for that, we would rather not to do that kind of changes.

Also, there is a lot of reuse of some strings (in string interpolation). it would be safer to keep them in a val/method

**Comment by igor-vovk** [comment]
Reason is to remove code duplication. Now host are not passed to *Request classes, and without host there is no so many need in `fullPathFor` methods.

As I can see, no public signatures is changed except apply methods. 
String parts are reused, but now this strings are not interpolated in runtime, which is faster.

**Comment by igor-vovk** [comment]
Oops

**Comment by pedrorijo91** [comment]
@johannegger take a look please

**Comment by johannegger** [comment]
Hi @igorynia, thank you for submitting this PR!
The implicit ConsulRequestBasics look fine to me. However I disagree on putting the prefix in every request. If you really don't like the fullPathFor defs please define the prefixes as constants in the objects.

**Comment by pedrorijo91** [comment]
is this to be closed @johannegger ?

**Comment by rtfpessoa** [comment]
Closing for inactivity

**Pull request closed without merging**
